version: "3.7"

services: 
    database_ignite:
        image: postgres
        container_name: database_quick_order
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=quick
            - POSTGRES_PASSWORD=order
            - POSTGRES_DB=quick_order
        volumes:
            - pgdata:/data/postgres
volumes:
    pgdata:
        driver: local